import {chromium} from '@playwright/test';
import {writeFileSync} from 'node:fs';
const base=process.env.BASE_URL??'http://127.0.0.1:3215';
const browser=await chromium.launch({headless:true,channel:"chromium"});
const page=await browser.newPage({viewport:{width:1400,height:1000}});
const findings=[];
page.on('pageerror',e=>findings.push('pageerror:'+e.message));
await page.goto(base);await page.getByText('ボードがありません',{exact:true}).waitFor();
findings.push('empty boards visible');
await page.getByLabel('新規ボード名',{exact:true}).fill('検証ボード');await page.getByRole('button',{name:'作成',exact:true}).click();
await page.getByRole('link',{name:'検証ボード',exact:true}).first().click();
await page.getByText('リストがありません',{exact:true}).waitFor(); findings.push('board URL '+new URL(page.url()).pathname);
await page.getByLabel('新規リスト名',{exact:true}).fill('未着手');await page.getByRole('button',{name:'作成',exact:true}).first().click();
await page.getByText('カードがありません',{exact:true}).waitFor();
await page.getByLabel('新規カード名',{exact:true}).fill('テストカード');await page.locator('.list').getByRole('button',{name:'作成',exact:true}).click();
await page.getByRole('button',{name:'テストカード',exact:true}).click();
const dialog=page.getByRole('dialog',{name:'カード詳細'});await dialog.waitFor();
await dialog.getByLabel('題名',{exact:true}).fill('更新カード');await dialog.getByLabel('説明',{exact:true}).fill('保存確認');await dialog.getByRole('button',{name:'保存',exact:true}).click();
await page.getByRole('button',{name:'更新カード',exact:true}).click();
if(await dialog.getByLabel('説明',{exact:true}).inputValue()!=='保存確認')throw Error('description did not persist');
await page.keyboard.press('Tab');findings.push('focus '+await page.evaluate(()=>document.activeElement?.tagName));
await page.keyboard.press('Escape');await dialog.waitFor({state:'hidden'});findings.push('dialog edited/reopened/Esc verified');
await page.screenshot({path:'evidence/section02-board.png'});
await page.getByRole('link',{name:'ボード一覧',exact:true}).first().click();await page.screenshot({path:'evidence/section02-list.png'});
if(findings.some(x=>x.startsWith('pageerror')))throw Error(findings.join('\n'));
writeFileSync('evidence/browser02.json',JSON.stringify(findings,null,2));console.log(findings);await browser.close();
